import type { SectorWorkflowTemplate, SafeSector } from '@/types/industry';

export const SECTOR_TEMPLATES: SectorWorkflowTemplate[] = [
  {
    id: 'wf-tourism-intake',
    sector: 'tourism',
    category: 'intake',
    name: 'Tourism Client Intake',
    description: 'Capture travel requirements, dates, budget, and preferences from new clients.',
    steps: [
      {
        id: 'wf-tourism-intake-1',
        sequence: 1,
        title: 'Collect Travel Brief',
        description: 'Gather destination, dates, group size, and budget range.',
        required_inputs: ['destination', 'travel_dates', 'group_size', 'budget'],
        expected_outputs: ['travel_brief'],
      },
      {
        id: 'wf-tourism-intake-2',
        sequence: 2,
        title: 'Confirm Requirements',
        description: 'Confirm special requirements such as accessibility or dietary needs.',
        required_inputs: ['travel_brief'],
        expected_outputs: ['confirmed_brief'],
      },
    ],
    estimated_duration_hours: 1,
    status: 'scaffolded',
  },
  {
    id: 'wf-ecommerce-production',
    sector: 'ecommerce',
    category: 'production',
    name: 'Product Listing Production',
    description: 'Draft, review, and publish product descriptions and images.',
    steps: [
      {
        id: 'wf-ecommerce-production-1',
        sequence: 1,
        title: 'Draft Product Copy',
        description: 'Write SEO-optimised product title and description.',
        required_inputs: ['product_name', 'product_specs', 'target_keywords'],
        expected_outputs: ['product_copy_draft'],
      },
      {
        id: 'wf-ecommerce-production-2',
        sequence: 2,
        title: 'Review and Approve',
        description: 'Client reviews draft and approves or requests revisions.',
        required_inputs: ['product_copy_draft'],
        expected_outputs: ['approved_copy'],
      },
    ],
    estimated_duration_hours: 2,
    status: 'scaffolded',
  },
  {
    id: 'wf-agencies-reporting',
    sector: 'agencies',
    category: 'reporting',
    name: 'Agency Monthly Report',
    description: 'Compile campaign performance data into a client-ready monthly report.',
    steps: [
      {
        id: 'wf-agencies-reporting-1',
        sequence: 1,
        title: 'Gather Performance Data',
        description: 'Pull metrics from relevant platforms and channels.',
        required_inputs: ['campaign_ids', 'reporting_period'],
        expected_outputs: ['raw_metrics'],
      },
      {
        id: 'wf-agencies-reporting-2',
        sequence: 2,
        title: 'Generate Report',
        description: 'Format metrics into branded report template.',
        required_inputs: ['raw_metrics', 'client_brand_kit'],
        expected_outputs: ['monthly_report'],
      },
    ],
    estimated_duration_hours: 3,
    status: 'scaffolded',
  },
  {
    id: 'wf-rem-outreach',
    sector: 'real_estate_marketing',
    category: 'outreach',
    name: 'Listing Outreach Campaign',
    description: 'Multi-channel outreach for new property listings.',
    steps: [
      {
        id: 'wf-rem-outreach-1',
        sequence: 1,
        title: 'Draft Listing Content',
        description: 'Write headline, body copy, and call-to-action for the listing.',
        required_inputs: ['property_details', 'target_audience'],
        expected_outputs: ['listing_content'],
      },
      {
        id: 'wf-rem-outreach-2',
        sequence: 2,
        title: 'Schedule Distribution',
        description: 'Schedule content across email, social, and portals.',
        required_inputs: ['listing_content', 'distribution_channels'],
        expected_outputs: ['scheduled_campaign'],
      },
    ],
    estimated_duration_hours: 2,
    status: 'scaffolded',
  },
  {
    id: 'wf-edu-production',
    sector: 'education_content',
    category: 'production',
    name: 'Lesson Production',
    description: 'Plan, script, and produce a single lesson module.',
    steps: [
      {
        id: 'wf-edu-production-1',
        sequence: 1,
        title: 'Lesson Planning',
        description: 'Define learning objectives, outline, and assessment criteria.',
        required_inputs: ['topic', 'target_audience', 'learning_objectives'],
        expected_outputs: ['lesson_plan'],
      },
      {
        id: 'wf-edu-production-2',
        sequence: 2,
        title: 'Script and Draft',
        description: 'Write lesson script and supporting materials.',
        required_inputs: ['lesson_plan'],
        expected_outputs: ['lesson_script', 'supporting_materials'],
      },
    ],
    estimated_duration_hours: 4,
    status: 'scaffolded',
  },
  {
    id: 'wf-sbo-reporting',
    sector: 'small_business_ops',
    category: 'reporting',
    name: 'Weekly Ops Summary',
    description: 'Compile weekly operational metrics into a concise summary.',
    steps: [
      {
        id: 'wf-sbo-reporting-1',
        sequence: 1,
        title: 'Collect Weekly Data',
        description: 'Gather sales, tasks completed, and open items for the week.',
        required_inputs: ['reporting_week'],
        expected_outputs: ['weekly_data'],
      },
      {
        id: 'wf-sbo-reporting-2',
        sequence: 2,
        title: 'Format Summary',
        description: 'Format into a one-page ops summary for the owner.',
        required_inputs: ['weekly_data'],
        expected_outputs: ['ops_summary'],
      },
    ],
    estimated_duration_hours: 1,
    status: 'scaffolded',
  },
];

export function getTemplatesBySector(sector: SafeSector): SectorWorkflowTemplate[] {
  return SECTOR_TEMPLATES.filter((t) => t.sector === sector);
}
